# 自动生成的皮肤配置文件 - 可手动编辑

[general]
enable_glow=true
custom_color=false

[short]
enable_color=false
color=#ffffff
random_color=false

[instant]
enable_color=false
color=#ffffff
random_color=false

[long]
enable_color=false
color=#ffffff
random_color=false
long_connect_mode=edge
long_f_mode=repeat
